Stat svc
alxdrvnk/java-explore-with-me pull request #3
Opened 2023-04-16 19:56 UTC by alxdrvnk

Add stats service

2023-04-17 14:41 UTC, alxdrvnk commented
Антон привет!

У меня возникла небольшая проблема. Почему то DbUnit не хотел заполнять базу и ругался на формат TIMESTAMP WITH TIME ZONE. Никак не пойму в чем дело.

2023-04-17 19:34 UTC, Donald522 requested changes
Привет!

Все отлично, давай только индексы добавим в таблицу.

2023-04-17 19:34 UTC, Donald522 commented on stats/service/src/main/java/ru.practicum.stats/repository/StatsRepository.java
> +    List<ViewStats> findByDateAndUnique(LocalDateTime start, LocalDateTime end, List<String> uris);
Можно было и не использовать hibernate, все равно все запросы вручную написал

2023-04-17 19:34 UTC, Donald522 commented on stats/service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS endpoint_hit (
Как минимум по uri и timestamp нужно добавить индексы, иначе наш сервис статистики будет довольно медленно работать

2023-04-17 19:34 UTC, Donald522 commented on stats/service/src/test/java/ru/practicum/stats/configuration/DbUnitConfig.java
> +        bean.setDatatypeFactory(new H2DataTypeFactory());
А почему тут h2?
Мы же делаем сервис на постгресе. Значит и тестировать надо на постгресе.
h2 может сильно отличаться.

2023-04-17 19:37 UTC, Donald522 commented
> Антон привет!
> 
> У меня возникла небольшая проблема. Почему то DbUnit не хотел заполнять базу и ругался на формат TIMESTAMP WITH TIME ZONE. Никак не пойму в чем дело.

Я бы начал с того, что поменял диалект DbUnit на постгрес. Возможно, в h2 и postgres надо немного по-разному этот тип в таблице указывать.

2023-04-18 17:30 UTC, alxdrvnk commented
Антон привет!

Вроде бы поправил проблему с DbUnit, но она исправилась как то очень странно. Я просто добавил .properties файл в папку с тестами и оно завелось. Ничего не понял.

Есть еще такой вопрос. По логике нужно же добавить индексы по всем полям?

2023-04-18 20:18 UTC, Donald522 approved these changes

2023-04-18 20:20 UTC, Donald522 commented
> Антон привет!
> 
> Вроде бы поправил проблему с DbUnit, но она исправилась как то очень странно. Я просто добавил .properties файл в папку с тестами и оно завелось. Ничего не понял.
> 
> Есть еще такой вопрос. По логике нужно же добавить индексы по всем полям?
> 
> P.S.: Хотел попробовать вместо H2 использовать библиотеку TestContainers, что бы тестировать на постгре, но вообще никак не получилось подключить зависимости. Ругался постоянно, что не может достучаться до удаленного репа.

Привет!

Индекс это не волшебная таблетка, помимо оптимизации чтения он также имеет свои недостатки - потребляет память, увеличивает время на запись. Как и во многом, создание индекса - это компромисс и не стоит делать это вслепую.
Вполне возможно, что индекс по app тут тоже пригодился бы.

2023-04-19 11:12 UTC, merged